language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never

before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - set -e

script:
  - cargo test
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings

after_script:
  - set +e
